routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


$languages = Config::get('app.locales');
$defaultLanguage = 'en';
if ($defaultLanguage) {
    $defaultLanguageCode = $defaultLanguage;
} 

$currentLanguageCode = Request::segment(1, $defaultLanguageCode);
if (in_array($currentLanguageCode, $languages)) {
    $defaultLanguageCode = $currentLanguageCode;
}

Route::group(['namespace' => 'Front', 'middleware' => 'front.lang'], function () use($defaultLanguageCode){
        App::setLocale($defaultLanguageCode);
        Route::get('getLocations/{country}', 'AjaxController@getLocations');
       
    

        Route::get('/', 'HomeController@index')->name('home');
    
        Auth::routes();



         /** profile */
        Route::get('profile', 'ProfileController@show')->name('front.user_profile');
        Route::get('profile/edit', 'ProfileController@edit')->name('front.edit_profile');
        Route::post('profile/edit', 'ProfileController@update')->name('front.update_profile');

       
});



Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('/change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::post('/change_sidebar_state', 'AjaxController@change_sidebar_state');
    Route::get('getCategories/{category_id}', 'AjaxController@getCategories');
    Route::get('getSpecialists/{category_id}', 'AjaxController@getSpecialists');
    Route::post('delete_image', 'AjaxController@deleteImage');
    Route::get('getLocations/{country}', 'AjaxController@getLocations');

    Route::get('statistics', 'AdminController@getStatistics')->name('statistics');

    Route::get('profile', 'ProfileController@index');
    Route::patch('profile', 'ProfileController@update');

    Route::resource('groups', 'GroupsController');
    Route::post('groups/data', 'GroupsController@data');

    Route::resource('admins', 'AdminsController');
    Route::post('admins/data', 'AdminsController@data');

    Route::resource('locations', 'LocationsController');
    Route::post('locations/data', 'LocationsController@data');  
    Route::resource('banners', 'BannersController');
    Route::post('banners/data', 'BannersController@data');  
    Route::resource('users', 'UsersController');
    Route::post('users/data', 'UsersController@data');
    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::post('settings', 'SettingsController@store');

    
    Route::group(['namespace' => 'Auth'], function() {

        Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'LoginController@login')->name('admin.login.submit');
        Route::get('logout', 'LoginController@logout')->name('admin.logout');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('admin.password.update');
    });
  
});

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Location extends MyModel {
    use SoftDeletes;
    protected $table = "locations";

    protected $casts = [
        'id' => 'integer'
    ];

    public static $sizes = array(
        's' => array('width' => 16, 'height' => 16),
        'm' => array('width' => 400, 'height' => 400)
    );

    public static function getAll($parent_id = 0) {
        return static::join('location_translations as trans', 'locations.id', '=', 'trans.location_id')
                        ->orderBy('locations.this_order', 'ASC')
                        ->where('locations.parent_id',$parent_id)
                        ->where('trans.locale', static::getLangCode())
                        ->select('locations.*','trans.title')
                        ->get();
    }

    public function childs() {
        return $this->hasMany(Location::class, 'parent_id');
    }

    public function translations() {
        return $this->hasMany(LocationTranslation::class, 'location_id');
    }


   public static function transform($item)
   {
       
       $transformer = new \stdClass();
       $transformer->id = $item->id;
       $transformer->title = $item->title;
       if ($item->parent_id == 0) {
            $transformer->dial_code = $item->dial_code;
            $transformer->image = url('public/uploads/locations') . '/' . str_replace('s_', 'm_', $item->image);
       }
       if ($item->childrens) {
          $transformer->childrens = $item->childrens;
       }
       return $transformer;
   }

    public static function transformFront($item)
    {
        $transformer = new \stdClass();
        $transformer->id = $item->id;
        $transformer->title = $item->title;
        if ($item->parent_id == 0) {
            $transformer->dial_code = $item->dial_code;
            $transformer->image = url('public/uploads/locations') . '/' . $item->image;
        }
        return $transformer;
    }

    protected static function boot() {
        parent::boot();

        static::deleting(function($location) {
            foreach ($location->translations as $translation) {
                $translation->delete();
            }
            foreach ($location->childs as $child) {
                $child->delete();
            }
            
        });

        static::deleted(function($location) {
            self::deleteUploaded('locations', $location->image);
        });
    }

}

app/Http/Controllers/Admin/LocationsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\BackendController;
use App\Models\Location;
use App\Models\LocationTranslation;
use Validator;
use DB;

class LocationsController extends BackendController {

    private $rules = array(
        'this_order' => 'required',
        'active'=>'required',
    );

    public function __construct() {

        parent::__construct();
        $this->middleware('CheckPermission:locations,open', ['only' => ['index']]);
        $this->middleware('CheckPermission:locations,add', ['only' => ['store']]);
        $this->middleware('CheckPermission:locations,edit', ['only' => ['show', 'update']]);
        $this->middleware('CheckPermission:locations,delete', ['only' => ['delete']]);
    }

    public function index(Request $request) {
        $parent_id = $request->input('parent') ? $request->input('parent') : 0;
        $this->data['path'] = $this->node_path($parent_id);
        $this->data['parent_id'] = $parent_id;
        return $this->_view('locations/index', 'backend');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request) {
        $parent_id = $request->input('parent') ? $request->input('parent') : 0;
        $this->data['path'] = $this->node_path($request->input('parent'),true);
        $this->data['parent_id'] = $parent_id;
        return $this->_view('locations/create', 'backend');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $columns_arr = array(
            'title' => 'required|unique:location_translations,title'
        );
        $lang_rules = $this->lang_rules($columns_arr);
        $this->rules = array_merge($this->rules, $lang_rules);
        $validator = Validator::make($request->all(), $this->rules);

        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }
        DB::beginTransaction();
        try {
            $location = new Location;
            $location->this_order = $request->input('this_order');
            $location->active = $request->input('active');
            $location->parent_id = $request->input('parent_id');
            if ($location->parent_id != 0) {
                $parent = Location::find($location->parent_id);
                $location->level = $parent->level + 1;
                if ($parent->parents_ids == null) {
                    $location->parents_ids = $parent->id;
                }
                else{
                    $parent_ids = explode(",",$parent->parents_ids);
                    array_push($parent_ids,$parent->id);
                    $location->parents_ids = implode(",", $parent_ids);
                }
            } else {
                $location->level = 1;
            }
            $location->save();

            $this->createLocationTranslations($location->id, $request);
            DB::commit();
            return _json('success', _lang('app.added_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            return _json('error', _lang('app.error_is_occured'), 400);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $find = Location::find($id);
        if ($find) {
            return _json('success', $find);
        } else {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $location = Location::find($id);
        if (!$location) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
        $this->data['path'] = $this->node_path($location->parent_id,true);
        $this->data['translations'] = LocationTranslation::where('location_id', $id)->get()->keyBy('locale');
        $this->data['parent_id'] = $location->parent_id;
        $this->data['location'] = $location;
       
        return $this->_view('locations/edit', 'backend');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $location = Location::find($id);
        if (!$location) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
        $columns_arr = array(
            'title' => 'required|unique:location_translations,title,' . $id . ',location_id'
        );
        
        $lang_rules = $this->lang_rules($columns_arr);
        $this->rules = array_merge($this->rules, $lang_rules);
        $validator = Validator::make($request->all(), $this->rules);

        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }


        DB::beginTransaction();
        try {
            $location->this_order = $request->input('this_order');
            $location->active = $request->input('active');
            $location->save();
            LocationTranslation::where('location_id', $location->id)->forceDelete();
            $this->createLocationTranslations($location->id, $request);
            
            DB::commit();
            return _json('success', _lang('app.updated_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            return _json('error', _lang('app.error_is_occured'), 400);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $location = Location::find($id);
        if (!$location) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
        DB::beginTransaction();
        try {
            $location->delete();
            DB::commit();
            return _json('success', _lang('app.deleted_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            if ($ex->getCode() == 23000) {
                return _json('error', _lang('app.this_record_can_not_be_deleted_for_linking_to_other_records'), 400);
            } else {
                return _json('error', _lang('app.error_is_occured'), 400);
            }
        }
    }

    private function createLocationTranslations($location_id, $request)
    {
        $location_translations = array();
        foreach ($request->input('title') as $key => $value) {
            $location_translations[] = array(
                'locale' => $key,
                'title' => $value,
                'location_id' => $location_id
            );
        }
        LocationTranslation::insert($location_translations);
    }

    public function data(Request $request) {

        $parent_id = $request->input('parent_id');
        if ($parent_id == 0) {
            $sql = '(select count(*) from users 
                join locations as cities on users.location_id = cities.id 
                join locations as countries on cities.parent_id = countries.id
                where countries.id = locations.id 
                group by countries.id)';
        }else{
            $sql = '(select count(*) from users 
                        join locations as cities on users.location_id = cities.id 
                        where cities.id = locations.id 
                        group by cities.id)';
        }
        $locations = Location::Join('location_translations', 'locations.id', '=', 'location_translations.location_id')
                ->where('locations.parent_id', $parent_id)
                ->where('location_translations.locale', $this->lang_code)
                ->select([
                    'locations.id', 
                    "location_translations.title",
                    "locations.this_order", 
                    'locations.level', 
                    'locations.parent_id', 
                    'locations.active', DB::raw("$sql as num_of_users")
                ]);
    

        return \DataTables::eloquent($locations)
                        ->addColumn('options', function ($item) {

                            $back = "";
                            if (\Permissions::check('locations', 'edit') || \Permissions::check('locations', 'delete')) {
                                $back .= '<div class="btn-group">';
                                $back .= ' <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> options';
                                $back .= '<i class="fa fa-angle-down"></i>';
                                $back .= '</button>';
                                $back .= '<ul class = "dropdown-menu" role = "menu">';
                                if (\Permissions::check('locations', 'edit')) {
                                    $back .= '<li>';
                                    $back .= '<a href="'.route('locations.edit',$item->id).'">';
                                    $back .= '<i class = "icon-docs"></i>' . _lang('app.edit');
                                    $back .= '</a>';
                                    $back .= '</li>';
                                }

                                if (\Permissions::check('locations', 'delete')) {
                                    $back .= '<li>';
                                    $back .= '<a href="" data-toggle="confirmation" onclick = "Locations.delete(this);return false;" data-id = "' . $item->id . '">';

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Http\Request;
use App\Traits\Basic;
use Auth;
use Image;

class BackendController extends Controller {

    use Basic;

    protected $lang_code = 'en';
    protected $User;
    protected $data = array();
    protected $limit = 3;

    public function __construct() {

        $this->middleware('auth:admin');
        
        $segment2 = \Request::segment(2);
        $this->data['page_link_name'] = $segment2;
        $this->User = Auth::guard('admin')->user();
        $this->data['User'] = $this->User;
        $this->data['languages'] = $this->languages;
        $this->getCookieLangAndSetLocale();
        $this->slugsCreate();
    }
    

    protected function getCookieLangAndSetLocale() {
        if (\Cookie::get('AdminLang') !== null) {
            try {
                $this->lang_code = \Crypt::decrypt(\Cookie::get('AdminLang'));

            } catch (DecryptException $ex) {
                $this->lang_code = 'en';
            }
        } else {
            $this->lang_code = 'en';
        }
        $this->data['lang_code'] = $this->lang_code;
        app()->setLocale($this->lang_code);
    }
   
   
    public function err404() {
        return $this->_view('err404','backend');
    }

}

resources/views/main_content/backend/locations/create.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.add_location'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
@if($path)
<li><a href="{{url('admin/locations')}}">{{_lang('app.locations')}}</a> <i class="fa fa-circle"></i></li>
{!!$path!!}
<li><span> {{_lang('app.create')}}</span></li>
@else
<li><span> {{_lang('app.locations')}}</span></li>
@endif
@endsection

@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form"  id="addEditLocationsForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.basic_info') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="0">

                @foreach ($languages as $key => $value)

                <div class="form-group form-md-line-input col-md-6">
                    <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]" value="">
                    <label for="title">{{_lang('app.title') }} {{ _lang('app. '.$value.'') }}</label>
                    <span class="help-block"></span>
                </div>

                @endforeach


            </div>
        </div>


    </div>

    <div class="panel panel-default">

        <div class="panel-body">


            <div class="form-body">
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="this_order" name="this_order" value="">
                    <label for="this_order">{{_lang('app.this_order') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-3">
                    <select class="form-control edited" id="active" name="active">
                        <option  value="1">{{ _lang('app.active') }}</option>
                        <option  value="0">{{ _lang('app.not_active') }}</option>
                    </select>
                     <label for="status">{{_lang('app.status') }}</label>
                    <span class="help-block"></span>
                </div> 
            </div>
        </div>
        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>

    </div>


</form>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};

</script>
@endsection

resources/views/main_content/backend/locations/edit.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.edit_location'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
@if($path)
<li><a href="{{url('admin/locations')}}">{{_lang('app.locations')}}</a> <i class="fa fa-circle"></i></li>
{!!$path!!}
<li><span> {{_lang('app.edit')}}</span></li>
@else
<li><span> {{_lang('app.locations')}}</span></li>
@endif
@endsection


@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form"  id="addEditLocationsForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.basic_info') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="{{ $location->id }}">

                @foreach ($languages as $key => $value)

                <div class="form-group form-md-line-input col-md-6">
                    <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]" value="{{ $translations["$key"]->title }}">
                    <label for="title">{{_lang('app.title') }} {{ _lang('app. '.$value.'') }}</label>
                    <span class="help-block"></span>
                </div>

                @endforeach
                <br>

            </div>
        </div>


    </div>


    <div class="panel panel-default">

        <div class="panel-body">


            <div class="form-body">

              

                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="this_order" name="this_order" value="{{ $location->this_order }}">
                    <label for="this_order">{{_lang('app.this_order') }}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3">
                    <select class="form-control edited" id="active" name="active">
                        <option  value="1" {{ $location->active == 1 ?'selected' : '' }}>{{ _lang('app.active') }}</option>
                        <option  value="0" {{ $location->active == 0 ?'selected' : '' }}>{{ _lang('app.not_active') }}</option>
                    </select>
                     <label for="status">{{_lang('app.status') }}</label>
                    <span class="help-block"></span>
                </div> 
               
               
            </div>
        </div>
     <div class="panel-footer text-center">
        <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
    </div>

    </div>



</form>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};

</script>
@endsection

resources/views/main_content/backend/locations/index.blade.php
@extends('layouts.backend')

@section('pageTitle', _lang('app.locations'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>

@if($path)
<li><a href="{{url('admin/locations')}}">{{_lang('app.locations')}}</a> <i class="fa fa-circle"></i></li>
{!!$path!!}
@else
<li><span> {{_lang('app.locations')}}</span></li>
@endif


@endsection

@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection
@section('content')

 {{ csrf_field() }}


<div class = "panel panel-default">

    <div class = "panel-body">


        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn green" style="margin-bottom: 40px;" href = "{{ route('locations.create') }}?parent={{ $parent_id }}" onclick="">{{ _lang('app.add_new')}}<i class="fa fa-plus"></i> </a>
                    </div>
                </div>
            </div>
        </div>

        <table class = "table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer">
            <thead>
                <tr>
                    <th>{{_lang('app.title')}}</th>
                    <th>{{_lang('app.active')}}</th>
                    <th>{{_lang('app.this_order')}}</th>
                    <th>{{_lang('app.number_of_users')}}</th>
                    <th>{{_lang('app.options')}}</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

        <!--Table Wrapper Finish-->
    </div>
</div>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};
</script>
@endsection