routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


$languages = Config::get('app.locales');
$defaultLanguage = 'en';
if ($defaultLanguage) {
    $defaultLanguageCode = $defaultLanguage;
} 

$currentLanguageCode = Request::segment(1, $defaultLanguageCode);
if (in_array($currentLanguageCode, $languages)) {
    $defaultLanguageCode = $currentLanguageCode;
}

Route::group(['namespace' => 'Front', 'middleware' => 'front.lang'], function () use($defaultLanguageCode){
        App::setLocale($defaultLanguageCode);
        Route::get('getLocations/{country}', 'AjaxController@getLocations');
       
    

        Route::get('/', 'HomeController@index')->name('home');
    
        Auth::routes();



         /** profile */
        Route::get('profile', 'ProfileController@show')->name('front.user_profile');
        Route::get('profile/edit', 'ProfileController@edit')->name('front.edit_profile');
        Route::post('profile/edit', 'ProfileController@update')->name('front.update_profile');

       
});



Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('/change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::post('/change_sidebar_state', 'AjaxController@change_sidebar_state');
    Route::get('getCategories/{category_id}', 'AjaxController@getCategories');
    Route::get('getSpecialists/{category_id}', 'AjaxController@getSpecialists');
    Route::post('delete_image', 'AjaxController@deleteImage');
    Route::get('getLocations/{country}', 'AjaxController@getLocations');

    Route::get('statistics', 'AdminController@getStatistics')->name('statistics');

    Route::get('profile', 'ProfileController@index');
    Route::patch('profile', 'ProfileController@update');

    Route::resource('groups', 'GroupsController');
    Route::post('groups/data', 'GroupsController@data');

    Route::resource('admins', 'AdminsController');
    Route::post('admins/data', 'AdminsController@data');

    Route::resource('locations', 'LocationsController');
    Route::post('locations/data', 'LocationsController@data');  
    Route::resource('banners', 'BannersController');
    Route::post('banners/data', 'BannersController@data');  
    Route::resource('users', 'UsersController');
    Route::post('users/data', 'UsersController@data');
    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::post('settings', 'SettingsController@store');

    
    Route::group(['namespace' => 'Auth'], function() {

        Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'LoginController@login')->name('admin.login.submit');
        Route::get('logout', 'LoginController@logout')->name('admin.logout');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('admin.password.update');
    });
  
});

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;

use Validator;
use App\Models\User;
use App\Models\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\BackendController;

class UsersController extends BackendController {

    private $rules = array(
        'name' => 'required',
        'email' => 'required|unique:users',
        'age' => 'required',
        'password' => 'required',
        'gender' => 'required',
        'country' => 'required',
        'city' => 'required',
        'active' => 'required',
        'image' => 'image|mimes:jpg,png,jpeg'
    );  
    public function __construct() {

        parent::__construct();
        $this->middleware('CheckPermission:users,open', ['only' => ['index']]);
        $this->middleware('CheckPermission:users,add', ['only' => ['create','store']]);
        $this->middleware('CheckPermission:users,edit', ['only' => ['edit', 'update']]);
        $this->middleware('CheckPermission:users,delete', ['only' => ['delete']]);
    }

    public function index(Request $request) {
        return $this->_view('users/index', 'backend');
    }
    public function create(Request $request) {
        $this->data['locations'] = Location::transformCollection(Location::getAll());
        return $this->_view('users/create', 'backend');
    }
    public function store(Request $request) {

        $validator = Validator::make($request->all(), $this->rules);
        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }
        DB::beginTransaction();
        try {
                $user = new User;
                $user->username = $request->input('name');
                $user->email = $request->input('email');
                if ($request->file('image')) {
                    $user->image = User::upload($request->file('image'), 'users', true);
                }else{
                    $user->image = 'default.png';
                }
                $user->age = $request->input('age');
                $user->password = bcrypt($request->input('password'));
                $user->gender = $request->input('gender');
                $user->location_id = $request->input('city');
                $user->save();
                DB::commit();
                return _json('success', _lang('app.added_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            return _json('error', _lang('app.error_is_occured'), 400);
        }
    }
    
 
    public function status($id){
        try {
            $user = User::find($id);
            $user->active = !$user->active;
            $user->save();
            return _json('success', _lang('app.success'));
        } catch (\Exception $e) {
            return _json('error', _lang('app.error_is_occured'));
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id) {
        $user = User::join('locations as city','city.id','=','users.location_id')
                    ->join('locations as country', 'country.id', '=', 'city.parent_id')
                    ->join('location_translations as city_trans',function($query){
                        $query->on('city_trans.location_id','=', 'city.id')
                        ->where('city_trans.locale',$this->lang_code);
                    })
                    ->join('location_translations as country_trans', function ($query) {
                        $query->on('country_trans.location_id', '=', 'country.id')
                            ->where('country_trans.locale', $this->lang_code);
                    })
                    ->select('users.*', 'country_trans.title as country', 'city_trans.title as city')
                    ->where('users.id',$id)
                    ->first();
        if (!$user) {
            return $this->err404();
        } 
        $this->data['user'] = $user;
        return $this->_view('users/show', 'backend');
    }
    public function edit($id)
    {
        try {
            $find = User::find($id);
            if (!$find) {
                return $this->err404();
            }
            $this->data['user'] = $find;
            $this->data['city'] = Location::where('id', $this->data['user']->location_id)->first();

            $this->data['locations'] = Location::getAll();
            $this->data['cities'] = Location::getAll($this->data['city']->parent_id);
            return $this->_view('users/edit', 'backend');
        } 
        catch (\Exception $ex){
            return $this->err404();
        }
    }
   

    public function update(Request $request, $id)
    {
        if ($request->input('password') === null) {
            unset($this->rules['password']);
        }
        $user= User::find($id);
        if (!$user) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
        $this->rules['password'] = 'min:6';
        $this->rules['email']= 'required|email|max:255|unique:users,email,'.$id.',id';

        $validator = Validator::make($request->all(), $this->rules);
        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }
        try {
           
            $user->username = $request->input('name');
            $user->email = $request->input('email');      
            $user->age = $request->input('age');
            if ($request->input('password') !== null) {
                $user->password = bcrypt($request->input('password'));
            }
            $user->gender = $request->input('gender');
            $user->location_id = $request->input('city');
            if ($request->file('image')) {
                if ($user->image != 'default.png') {
                    User::deleteUploaded('users',$user->image);
                }
                $user->image = User::upload($request->file('image'), 'users', true);
            } 
            $user->save(); 
            return _json('success', _lang('app.updated_successfully'));
        } catch (\Exception $ex) {
            return _json('error', _lang('app.error_is_occured'), 400);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id) {
        $user = User::find($id);
        if ($user == null) {
            return _json('error', _lang('app.error_is_occured'));
        }
        try {
            $user->delete();
            return _json('success', _lang('app.deleted_successfully'));
        } catch (\Exception $ex) {
            if ($ex->getCode() == 23000) {
                return _json('error', _lang('app.this_record_can_not_be_deleted_for_linking_to_other_records'), 400);
            } else {
                return _json('error', _lang('app.error_is_occured'), 400);
            }
        }
    }



    public function data(Request $request) {
        $users = User::select(['id','username', 'email','active','image','gender']);

        return \DataTables::eloquent($users)
                ->addColumn('options', function ($item){
                    $js='Users';
                    $back = "";
                          
                        if (\Permissions::check('articles', 'edit') ||\Permissions::check('users', 'open')) {
                            $back .= '<div class="btn-group">';
                            $back .= ' <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> options';
                            $back .= '<i class="fa fa-angle-down"></i>';
                            $back .= '</button>';
                            $back .= '<ul class = "dropdown-menu" role = "menu">';
                            if (\Permissions::check('users', 'open')) {
                                $back .= '<li>';
                                $back .= '<a href="'.route('users.show',$item->id).'" onclick = "" data-id = "' . $item->id . '">';
                                $back .= '<i class = "icon-docs"></i>' . _lang('app.show');
                                $back .= '</a>';
                                $back .= '</li>';
                            }
                            if (\Permissions::check('users', 'edit')) {
                                $back .= '<li>';
                                $back .= '<a href="' . route('users.edit', $item->id) . '">';
                                $back .= '<i class = "icon-docs"></i>' . _lang('app.edit');
                                $back .= '</a>';
                                $back .= '</li>';
                            }
                            $back .= '</ul>';
                            $back .= ' </div>';
                        }
                    return $back;
                })
                ->editColumn('active', function ($item) {
                    if ($item->active == 1) {
                        $message = _lang('app.active');
                        $class = 'btn-info';
                    } else {
                        $message = _lang('app.not_active');
                        $class = 'btn-danger';
                    }
                    $back = '<a class="btn ' . $class . '" onclick = "Users.status(this);return false;" data-id = "' . $item->id . '" data-status = "' . $item->active . '">' . $message . ' <a>';
                    return $back;
                })
                ->editColumn('gender', function ($item) {
                    if ($item->gender == User::$gender['male']) {
                        $class = 'fa fa-male';
                    } else {
                        $class = 'fa fa-female';
                    }
                    $back = '<div style="margin-top:2%"><i class="' . $class . ' fa-2x"></i></div>';
                    return $back;

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Http\Request;
use App\Traits\Basic;
use Auth;
use Image;

class BackendController extends Controller {

    use Basic;

    protected $lang_code = 'en';
    protected $User;
    protected $data = array();
    protected $limit = 3;

    public function __construct() {

        $this->middleware('auth:admin');
        
        $segment2 = \Request::segment(2);
        $this->data['page_link_name'] = $segment2;
        $this->User = Auth::guard('admin')->user();
        $this->data['User'] = $this->User;
        $this->data['languages'] = $this->languages;
        $this->getCookieLangAndSetLocale();
        $this->slugsCreate();
    }
    

    protected function getCookieLangAndSetLocale() {
        if (\Cookie::get('AdminLang') !== null) {
            try {
                $this->lang_code = \Crypt::decrypt(\Cookie::get('AdminLang'));

            } catch (DecryptException $ex) {
                $this->lang_code = 'en';
            }
        } else {
            $this->lang_code = 'en';
        }
        $this->data['lang_code'] = $this->lang_code;
        app()->setLocale($this->lang_code);
    }
   
   
    public function err404() {
        return $this->_view('err404','backend');
    }

}

resources/views/main_content/backend/users/create.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.add_user'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>

<li><a href="{{route('users.index')}}">{{_lang('app.users')}}</a> <i class="fa fa-circle"></i></li>

<li><span> {{_lang('app.create')}}</span></li>

@endsection

@section('js')
<script src="{{url('public/backend/js')}}/users.js" type="text/javascript"></script>
@endsection
@section('content')
<form method="" action="" id="addEditUsersForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.basic_info') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="0">

                <div class="form-group form-md-line-input col-md-4">
                    <input type="text" placeholder="{{_lang('app.name')}}" class="form-control" name="name" id="name">
                    <label for="name">{{_lang('app.name') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-4">
                    <input type="email" placeholder="{{_lang('app.email')}}" class="form-control" name="email" id="email">
                    <label for="email">{{_lang('app.email') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-4">
                    <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="{{_lang('app.password')}}" name="password" id="password" />
                    <label>{{_lang('app.password')}}</label>
                    <span class="help-block"></span>
                </div>

                        <div class="form-group form-md-line-input col-md-6">
                            <label class="control-label">{{_lang('app.image')}}</label>
                        
                            <div class="image_box">
                                <img src="{{url('no-image.png')}}" width="100" height="80" class="image" />
                            </div>
                            <input type="file" name="image" id="image" style="visibility: hidden">
                            <span class="help-block"></span>
                        </div>

                        <div class="form-group form-md-line-input col-md-2 select">
                            <select class="form-control edited" id="active" name="active">
                                <option value="1">{{ _lang('app.active') }}</option>
                                <option value="0">{{ _lang('app.not_active') }}</option>
                            </select>
                            <label for="status">{{_lang('app.status') }}</label>
                            <span class="help-block"></span>
                        </div>

                        
                    
                
               

            </div>
        </div>
    </div>
     

   
    <div class="panel panel-default">
       <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.personal_info')}}</h3>
        </div>
        <div class="panel-body">
            <div class="form-body">
                
                <div class="form-group form-md-line-input col-md-2">
                    <input type="number" placeholder="{{_lang('app.age')}}" class="form-control" name="age" id="age">
                    <label>{{_lang('app.age')}}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-2 select">
                    <select class="form-control edited" id="gender" name="gender">
                            <option value="">{{_lang('app.choose')}}</option>
                            <option value="1">{{_lang('app.male')}}</option>
                            <option value="2">{{_lang('app.female')}}</option>
                    </select>
                    <label for="gender">{{_lang('app.gender') }}</label>
                    <span class="help-block"></span>
                </div> 
                <div class="form-group form-md-line-input col-md-3 select">
                        <select class="form-control edited" id="country" name="country">
                            <option value="">{{_lang('app.choose')}}</option>
                            @foreach ($locations as $location)
                            <option value="{{$location->id}}">{{$location->title}}</option>
                            @endforeach
                        </select>
                        <label for=" country">{{_lang('app.country') }}</label>
                        <span class="help-block"></span>
                </div>
                
                <div class="form-group form-md-line-input col-md-3 select">
                        <select class="form-control edited" id="city" name="city">
                            <option value="">{{_lang('app.choose')}}</option>
                        </select>
                        <label for=" city">{{_lang('app.city') }}</label>
                        <span class="help-block"></span>
                </div>
            </div>
        </div>

    <div class="panel panel-default">
         <div class="panel-heading">
            
        </div>
        <div class="panel-body">
            
        </div>
        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>
    
    </div>

</form>
<script>
var new_lang = {

};
var new_config = {
    
};

</script>
@endsection

resources/views/main_content/backend/users/edit.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.edit_user'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>

<li><a href="{{route('users.index')}}">{{_lang('app.users')}}</a> <i class="fa fa-circle"></i></li>

<li><span> {{_lang('app.edit')}}</span></li>

<li><span> {{_lang('app.users')}}</span></li>

@endsection

@section('js')
<script src="{{url('public/backend/js')}}/users.js" type="text/javascript"></script>
@endsection
@section('content')
<form method="" action="" id="addEditUsersForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.basic_info') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="{{$user->id}}">

            <div class="form-group form-md-line-input col-md-3">
                <input type="text" placeholder="{{_lang('app.name')}}" value="{{$user->username}}" class="form-control" name="name" id="name">
                <label for="name">{{_lang('app.name') }}</label>
                <span class="help-block"></span>
            </div>
            
            <div class="form-group form-md-line-input col-md-3">
                <input type="email" placeholder="{{_lang('app.email')}}" value="{{$user->email}}" class="form-control" name="email" id="email">
                <label for="email">{{_lang('app.email') }}</label>
                <span class="help-block"></span>
            </div>
            
            <div class="form-group form-md-line-input col-md-4">
                <label class="control-label">{{_lang('app.image')}}</label>
            
                <div class="image_box">
                    <img src="{{url('public/uploads/users/'.$user->image)}}" width="100" height="80" class="image" />
                </div>
                <input type="file" name="image" id="image" style="visibility: hidden">
                <span class="help-block"></span>
            </div>
            
            <div class="form-group form-md-line-input col-md-2 select">
                <select class="form-control edited" id="active" name="active">
                    <option value="1" {{$user->active == 1 ? 'selected' : ''}}>{{ _lang('app.active') }}</option>
                    <option value="0" {{$user->active == 0 ? 'selected' : ''}}>{{ _lang('app.not_active') }}</option>
                </select>
                <label for="status">{{_lang('app.status') }}</label>
                <span class="help-block"></span>
            </div>




            </div>
        </div>
    </div>



    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.personal_info')}}</h3>
        </div>
        <div class="panel-body">
            <div class="form-body">

                <div class="form-group form-md-line-input col-md-2">
                    <input type="number" value="{{$user->age}}"  placeholder="{{_lang('app.age')}}" class="form-control" name="age" id="age">
                    <label>{{_lang('app.age')}}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-2 select">
                    <select class="form-control edited" id="gender" name="gender">
                        <option value="">{{_lang('app.choose')}}</option>
                        <option value="1" {{$user->gender == 1 ? 'selected' : ''}}>{{_lang('app.male')}}</option>
                        <option value="2" {{$user->gender == 2 ? 'selected' : ''}}>{{_lang('app.female')}}</option>
                    </select>
                    <label for="gender">{{_lang('app.gender') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="country" name="country">
                        <option value="">{{_lang('app.choose')}}</option>
                        @foreach ($locations as $location)
                        <option value="{{$location->id}}" {{$city->parent_id == $location->id ? 'selected' : ''}}>{{$location->title}}</option>
                        @endforeach
                    </select>
                    <label for=" country">{{_lang('app.country') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="city" name="city">
                        <option value="">{{_lang('app.choose')}}</option>
                        @foreach ($cities as $city)
                        <option value="{{$city->id}}" {{$city->id == $user->location_id ? 'selected' : ''}}>{{$city->title}}</option>
                        @endforeach
                    </select>
                    <label for=" city">{{_lang('app.city') }}</label>
                    <span class="help-block"></span>
                </div>
            </div>
           
        </div>
        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>
    </div>

</form>
<script>
    var new_lang = {

};
var new_config = {
    
};

</script>
@endsection

resources/views/main_content/backend/users/index.blade.php
@extends('layouts.backend')

@section('pageTitle', _lang('app.users'))
@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
<li><span> {{_lang('app.users')}}</span></li>
@endsection
@section('js')

<script src="{{url('public/backend/js')}}/users.js" type="text/javascript"></script>
@endsection
@section('content')
{{ csrf_field() }}
<div class = "panel panel-default">
    <div class = "panel-body">
    <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn green" style="margin-bottom: 40px;" href = "{{ route('users.create') }}" onclick="">{{ _lang('app.add_new')}}<i class="fa fa-plus"></i> </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div id="" class="table-container">
            
            <table class = "table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer">
                <thead>
                    <tr>
                        <th>{{ _lang('app.username') }}</th>
                        <th>{{ _lang('app.email') }}</th>
                        <th>{{_lang('app.image')}}</th>
                        <th>{{_lang('app.gender')}}</th>
                        <th>{{_lang('app.status')}}</th>
                        <th>{{_lang('app.options')}}</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    
        </div> 


        <!--Table Wrapper Finish-->
    </div>
</div>
<script>
    var new_config = {
        
    };
</script>
@endsection