routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


$languages = Config::get('app.locales');
$defaultLanguage = 'en';
if ($defaultLanguage) {
    $defaultLanguageCode = $defaultLanguage;
} 

$currentLanguageCode = Request::segment(1, $defaultLanguageCode);
if (in_array($currentLanguageCode, $languages)) {
    $defaultLanguageCode = $currentLanguageCode;
}

Route::group(['namespace' => 'Front', 'middleware' => 'front.lang'], function () use($defaultLanguageCode){
        App::setLocale($defaultLanguageCode);
        Route::get('getLocations/{country}', 'AjaxController@getLocations');
       
    

        Route::get('/', 'HomeController@index')->name('home');
    
        Auth::routes();



         /** profile */
        Route::get('profile', 'ProfileController@show')->name('front.user_profile');
        Route::get('profile/edit', 'ProfileController@edit')->name('front.edit_profile');
        Route::post('profile/edit', 'ProfileController@update')->name('front.update_profile');

       
});



Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('/change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::post('/change_sidebar_state', 'AjaxController@change_sidebar_state');
    Route::get('getCategories/{category_id}', 'AjaxController@getCategories');
    Route::get('getSpecialists/{category_id}', 'AjaxController@getSpecialists');
    Route::post('delete_image', 'AjaxController@deleteImage');
    Route::get('getLocations/{country}', 'AjaxController@getLocations');

    Route::get('statistics', 'AdminController@getStatistics')->name('statistics');

    Route::get('profile', 'ProfileController@index');
    Route::patch('profile', 'ProfileController@update');

    Route::resource('groups', 'GroupsController');
    Route::post('groups/data', 'GroupsController@data');

    Route::resource('admins', 'AdminsController');
    Route::post('admins/data', 'AdminsController@data');

    Route::resource('locations', 'LocationsController');
    Route::post('locations/data', 'LocationsController@data');  
    Route::resource('banners', 'BannersController');
    Route::post('banners/data', 'BannersController@data');  
    Route::resource('users', 'UsersController');
    Route::post('users/data', 'UsersController@data');
    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::post('settings', 'SettingsController@store');

    
    Route::group(['namespace' => 'Auth'], function() {

        Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'LoginController@login')->name('admin.login.submit');
        Route::get('logout', 'LoginController@logout')->name('admin.logout');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('admin.password.update');
    });
  
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Banner extends MyModel 
{
    protected $table = "banners";
    public function location()
    {
        return $this->belongsTo(Location::class,'location_id');
    }
    public function translations() {
        return $this->hasMany(BannerTranslations::class, 'banner_id');
    }
    protected static function boot() {
        parent::boot();

        static::deleting(function($banner) {
            foreach ($banner->translations as $translation) {
                $translation->delete();
            }
        });

        static::deleted(function($banner) {
            self::deleteUploaded('banners', $banner->image);
        });
    }
}

app/Http/Controllers/Admin/BannersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\BackendController;
use DB;
use Validator;
use App\Models\Banner;
use App\Models\BannerTranslations;
use App\Models\Location;

class BannersController extends BackendController
{
    private $rules = array(
        'active'       => 'required',
        'this_order'       => 'required',
        'image' => 'required|image|mimes:gif,png,jpeg|max:1000',
        
    );
    public function __construct()
    {
        parent::__construct();
        $this->middleware('CheckPermission:banners,open', ['only' => ['index']]);
        $this->middleware('CheckPermission:banners,add', ['only' => ['store']]);
        $this->middleware('CheckPermission:banners,edit', ['only' => ['show', 'update']]);
        $this->middleware('CheckPermission:banners,delete', ['only' => ['delete']]);
    }
   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->_view('banners/index', 'backend');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['locations'] = Location::transformCollection(Location::getAll());
        return $this->_view('banners/create', 'backend');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $columns_arr = array(
            'title' => 'required|unique:banner_translations,title',
            
        );
        $lang_rules = $this->lang_rules($columns_arr);
        $this->rules = array_merge($this->rules, $lang_rules);
        $validator = Validator::make($request->all(), $this->rules);
        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }
        DB::beginTransaction();
        try {

            $banner= new Banner;
            $banner->active = $request->input('active');
            $banner->this_order = $request->input('this_order');
            $banner->duration = $request->input('duration');
            $banner->frequency = $request->input('frequency');
            $banner->image =Banner::upload($request->file('image'), 'banners', true);
            $banner->location_id = $request->input('city');
            $banner->save();

            $this->createbannerTranslations($banner->id, $request);
           
           
            DB::commit();
            return _json('success', _lang('app.added_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            return _json('error', _lang('app.error_is_occured'), 400);
        }
    }
    public function edit($id)
    {
        $find = banner::find($id);
        if (!$find) {
            return $this->err404();
        }
        $this->data['banner'] = $find;
        $this->data['city'] = Location::where('id', $this->data['banner']->location_id)->first();

        $this->data['locations'] = Location::getAll();
        $this->data['cities'] = Location::getAll($this->data['city']->parent_id);
        $this->data['translations'] = BannerTranslations::where('banner_id', $id)->get()->keyBy('locale');
        return $this->_view('banners/edit', 'backend');
    }


    public function update(Request $request, $id)
    {
        $banner= Banner::find($id);
        if (!$banner) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }

        $this->rules['image'] = 'image|mimes:gif,png,jpeg|max:1000';

        $columns_arr = array(
            'title' => 'required|unique:banner_translations,title,' . $id . ',banner_id',
            
    
        );

        $lang_rules = $this->lang_rules($columns_arr);
        $this->rules = array_merge($this->rules, $lang_rules);
        $validator = Validator::make($request->all(), $this->rules);

        if ($validator->fails()) {
            $errors = $validator->errors()->toArray();
            return _json('error', $errors);
        }
        DB::beginTransaction();
        try {

            $banner->active = $request->input('active');
            $banner->this_order = $request->input('this_order');
            $banner->duration = $request->input('duration');
            $banner->frequency = $request->input('frequency');
            $banner->location_id = $request->input('city');

            if ($request->file('image')) {
                banner::deleteUploaded('banner', $banner->image);
                $banner->image = Banner::upload($request->file('image'), 'banner', true);
            }

            $banner->save();

            bannerTranslations::where('banner_id', $banner->id)->forceDelete();
            $this->createbannerTranslations($banner->id, $request);
            DB::commit();
            return _json('success',  _lang('app.updated_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            return _json('error', $ex->getMessage(), 400);
        }
    }
    public function destroy($id)
    {
        $banner= banner::find($id);
        if (!$banner) {
            return _json('error', _lang('app.error_is_occured'), 404);
        }
        DB::beginTransaction();
        try {
            $banner->delete();
            DB::commit();
            return _json('success', _lang('app.deleted_successfully'));
        } catch (\Exception $ex) {
            DB::rollback();
            if ($ex->getCode() == 23000) {
                return _json('error', _lang('app.this_record_can_not_be_deleted_for_linking_to_other_records'), 400);
            } else {
                return _json('error', _lang('app.error_is_occured'), 400);
            }
        }
    }
    private function createbannerTranslations($banner_id, $request)
    {
        $banner_translations = array();
        $title = $request->input('title');
        $description = $request->input('description');
       
        foreach ($title as $key => $value) {
            $banner_translations[] = array(
                'locale' => $key,
                'title' => $value,
                'description'=> $description[$key],
                'banner_id' => $banner_id
            );
        }
        BannerTranslations::insert($banner_translations);
    }
    public function data(Request $request)
    {
        $banner = Banner::Join('banner_translations', 'banners.id', '=', 'banner_translations.banner_id')
            ->where('banner_translations.locale', $this->lang_code)
            ->select([
                'banners.id', 'banners.image', "banner_translations.title", "banners.active", "banners.duration"
            ]);
        return \DataTables::eloquent($banner)
            ->addColumn('options', function ($item) {

                $back = "";
                if (\Permissions::check('banners', 'edit') || \Permissions::check('banners', 'delete')) {
                    $back .= '<div class="btn-group">';
                    $back .= ' <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">' . _lang('app.options');
                    $back .= '<i class="fa fa-angle-down"></i>';
                    $back .= '</button>';
                    $back .= '<ul class = "dropdown-menu" role = "menu">';
                    if (\Permissions::check('banners', 'edit')) {
                        $back .= '<li>';
                        $back .= '<a href="' . route('banners.edit', $item->id) . '">';
                        $back .= '<i class = "icon-docs"></i>' . _lang('app.edit');
                        $back .= '</a>';
                        $back .= '</li>';
                    }

                    if (\Permissions::check('banners', 'delete')) {
                        $back .= '<li>';
                        $back .= '<a href="" data-toggle="confirmation" onclick = "Banner.delete(this);return false;" data-id = "' . $item->id . '">';
                        $back .= '<i class = "icon-docs"></i>' . _lang('app.delete');
                        $back .= '</a>';
                        $back .= '</li>';
                    }

                    $back .= '</ul>';
                    $back .= ' </div>';
                }
                return $back;
            })
            ->addColumn('active', function ($item) {
                if ($item->active == 1) {
                    $message = _lang('app.active');
                    $class = 'label-success';
                } else {
                    $message = _lang('app.not_active');
                    $class = 'label-danger';
                }
                $back = '<span class="label label-sm ' . $class . '">' . $message . '</span>';
                return $back;
            })
            ->editColumn('image', function ($item) {
                $back = '<img src="' . url('public/uploads/banners/' . $item->image) . '" style="height:100px;width:400px;"/>';
                return $back;
            })
            ->escapeColumns([])
            ->make(true);
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Http\Request;
use App\Traits\Basic;
use Auth;
use Image;

class BackendController extends Controller {

    use Basic;

    protected $lang_code = 'en';
    protected $User;
    protected $data = array();
    protected $limit = 3;

    public function __construct() {

        $this->middleware('auth:admin');
        
        $segment2 = \Request::segment(2);
        $this->data['page_link_name'] = $segment2;
        $this->User = Auth::guard('admin')->user();
        $this->data['User'] = $this->User;
        $this->data['languages'] = $this->languages;
        $this->getCookieLangAndSetLocale();
        $this->slugsCreate();
    }
    

    protected function getCookieLangAndSetLocale() {
        if (\Cookie::get('AdminLang') !== null) {
            try {
                $this->lang_code = \Crypt::decrypt(\Cookie::get('AdminLang'));

            } catch (DecryptException $ex) {
                $this->lang_code = 'en';
            }
        } else {
            $this->lang_code = 'en';
        }
        $this->data['lang_code'] = $this->lang_code;
        app()->setLocale($this->lang_code);
    }
   
   
    public function err404() {
        return $this->_view('err404','backend');
    }

}

resources/views/main_content/backend/banners/create.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.add_banner'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>

<li><a href="{{route('banners.index')}}">{{_lang('app.banners')}}</a> <i class="fa fa-circle"></i></li>

<li><span> {{_lang('app.create')}}</span></li>

<li><span> {{_lang('app.banner')}}</span></li>

@endsection

@section('js')
<script src="{{url('public/backend/js')}}/banners.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form"  id="addEditBannerForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_title') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="0">

                <div class="form-body">
                    @foreach ($languages as $key => $value)
                
                    <div class="form-group form-md-line-input col-md-6">
                        <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]" value="">
                        <label for="title">{{_lang('app.title') }} {{ _lang('app.'.$value.'') }}</label>
                        <span class="help-block"></span>
                    </div>
                
                    @endforeach
                
                </div>
               

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_description') }}</h3>
        </div>
        <div class="panel-body">
    
    
            <div class="form-body">
               
    
                <div class="form-body">
                    @foreach ($languages as $key => $value)
    
                    <div class="form-group form-md-line-input col-md-6">
                        <textarea class="form-control" id="description[{{ $key }}]" name="description[{{ $key }}]" rows="7"></textarea>
                        <label for="description">{{_lang('app.description') }} {{ _lang('app.'.$value.'') }}</label>
                        <span class="help-block"></span>
                    </div>
    
                    @endforeach
    
                </div>
    
    
            </div>
        </div>
    </div>
     
    
   


    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_photo') }}</h3>
        </div>
        <div class="panel-body">
    
            <div class="form-body">
            <h4 class="text-info">Hints:</h4>
           <h5>Minimum image size : 1130x474.15</h5>
          
                <div class="form-group form-md-line-input col-md-2">
                        <div class="image_box">
                            <img src="{{url('no-image.png')}}" width="100" height="80" class="image" />
                        </div>
                        <input type="file" name="image" id="image" style="visibility: hidden">
                        <span class="help-block"></span>
                </div>
           
               
                <div class="clearfix"></div>
                <hr>
               
        
            </div>
        </div>
    
    </div>

   
    <div class="panel panel-default">
       <div class="panel-heading">
       <h3 class="panel-title"></h3>
            </div>
        <div class="panel-body">

         
            <div class="form-body">

              
               
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="this_order" name="this_order" value="">
                    <label for="this_order">{{_lang('app.this_order') }}</label>
                    <span class="help-block"></span>
                </div>
                
                <div class="form-group form-md-line-input col-md-3">
                    <select class="form-control edited" id="active" name="active">
                        <option  value="1">{{ _lang('app.active') }}</option>
                        <option  value="0">{{ _lang('app.not_active') }}</option>
                    </select>
                     <label for="status">{{_lang('app.status') }}</label>
                    <span class="help-block"></span>
                </div> 
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="duration" name="duration" value="">
                    <label for="duration">{{_lang('app.duration') }}</label>
                    <h6>hint: add duration in milliseconds</h6>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="frequency" name="frequency" value="">
                    <label for="frequency">{{_lang('app.frequency_of_appearance') }}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="country" name="country">
                        <option value="">{{_lang('app.choose')}}</option>
                        @foreach ($locations as $location)
                        <option value="{{$location->id}}">{{$location->title}}</option>
                        @endforeach
                    </select>
                    <label for=" country">{{_lang('app.country') }}</label>
                    <span class="help-block"></span>
            </div>
            
            <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="city" name="city">
                        <option value="">{{_lang('app.choose')}}</option>
                    </select>
                    <label for=" city">{{_lang('app.city') }}</label>
                    <span class="help-block"></span>
            </div>

            </div>
        </div>

         <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form"
                    >{{_lang('app.save') }}</button>
        </div>


    </div>


</form>
<script>
var new_lang = {

};
var new_config = {
    
};

</script>
@endsection

resources/views/main_content/backend/banners/edit.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.edit_banner'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>

<li><a href="{{route('banners.index')}}">{{_lang('app.banners')}}</a> <i class="fa fa-circle"></i></li>

<li><span> {{_lang('app.edit')}}</span></li>

<li><span> {{_lang('app.banner')}}</span></li>

@endsection

@section('js')
<script src="{{url('public/backend/js')}}/banners.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form" id="addEditBannerForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_title') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="{{ $banner->id }}">

                <div class="form-body">
                    @foreach ($languages as $key => $value)

                    <div class="form-group form-md-line-input col-md-6">
                        <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]"
                            value="{{ $translations["$key"]->title }}">
                        <label for="title">{{_lang('app.title') }} {{ _lang('app.'.$value.'') }}</label>
                        <span class="help-block"></span>
                    </div>

                    @endforeach

                </div>


            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_description') }}</h3>
        </div>
        <div class="panel-body">
    
    
            <div class="form-body">
                <input type="hidden" name="id" id="id" value="0">
    
                <div class="form-body">
                    @foreach ($languages as $key => $value)
    
                    <div class="form-group form-md-line-input col-md-6">
                        <textarea  class="form-control" id="description[{{ $key }}]" name="description[{{ $key }}]"
                            rows="7">{{ $translations["$key"]->description }}</textarea>
                        <label for="description">{{_lang('app.description') }} {{ _lang('app.'.$value.'') }}</label>
                        <span class="help-block"></span>
                    </div>
    
                    @endforeach
    
                </div>
    
    
            </div>
        </div>
    </div>





    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.banner_photo') }}</h3>
        </div>
        <div class="panel-body">

            <div class="form-body">
            <h4 class="text-info">Hints:</h4>
           <h5>Minimum image size : 1130x474.15</h5>

                <div class="form-group form-md-line-input col-md-2">
                    <div class="image_box">
                       <img src="{{url('public/uploads/banners').'/'.$banner->image}}" width="100" height="80" class="image" />
                    </div>
                    <input type="file" name="image" id="image" style="visibility: hidden">
                    <span class="help-block"></span>
                </div>


                <div class="clearfix"></div>
                <hr>


            </div>
        </div>

    </div>


    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"></h3>
        </div>
        <div class="panel-body">


            <div class="form-body">



                <div class="form-group form-md-line-input col-md-3">
                <input type="number" class="form-control" id="this_order" name="this_order" value="{{$banner->this_order}}">
                    <label for="this_order">{{_lang('app.this_order') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-3">
                    <select class="form-control edited" id="active" name="active">
                       <option value="1" {{ $banner->active == 1 ?'selected' : '' }}>{{ _lang('app.active') }}</option>
                        <option value="0" {{ $banner->active == 0 ?'selected' : '' }}>{{ _lang('app.not_active') }}</option>
                    </select>
                    <label for="status">{{_lang('app.status') }}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="duration" name="duration" value="{{$banner->duration}}">
                    <label for="duration">{{_lang('app.duration') }}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3">
                    <input type="number" class="form-control" id="frequency" name="frequency" value="{{$banner->frequency}}">
                    <label for="frequency">{{_lang('app.frequency_of_appearance') }}</label>
                    <span class="help-block"></span>
                </div>
                <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="country" name="country">
                        <option value="">{{_lang('app.choose')}}</option>
                        @foreach ($locations as $location)
                        <option value="{{$location->id}}" {{$city->parent_id == $location->id ? 'selected' : ''}}>{{$location->title}}</option>
                        @endforeach
                    </select>
                    <label for=" country">{{_lang('app.country') }}</label>
                    <span class="help-block"></span>
                </div>

                <div class="form-group form-md-line-input col-md-3 select">
                    <select class="form-control edited" id="city" name="city">
                        <option value="">{{_lang('app.choose')}}</option>
                        @foreach ($cities as $city)
                        <option value="{{$city->id}}" {{$city->id == $banner->location_id ? 'selected' : ''}}>{{$city->title}}</option>
                        @endforeach
                    </select>
                    <label for=" city">{{_lang('app.city') }}</label>
                    <span class="help-block"></span>
                </div>

            </div>
        </div>

        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>


    </div>


</form>
<script>
    var new_lang = {

};
var new_config = {
    
};

</script>
@endsection

resources/views/main_content/backend/banners/index.blade.php
@extends('layouts.backend')

@section('pageTitle', _lang('app.banner'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>


<li><span> {{_lang('app.banner')}}</span></li>


@endsection

@section('js')
<script src="{{url('public/backend/js')}}/banners.js" type="text/javascript"></script>
@endsection
@section('content')


<div class = "panel panel-default">
{{ csrf_field() }}
    <div class = "panel-body">


        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn green" style="margin-bottom: 40px;" href = "{{ route('banners.create') }}" onclick="">{{ _lang('app.add_new')}}<i class="fa fa-plus"></i> </a>
                    </div>
                </div>
            </div>
        </div>

        <table class = "table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer">
            <thead>
                <tr>
                    <th>{{_lang('app.title')}}</th>
                    <th>{{_lang('app.image')}}</th>
                    <th>{{_lang('app.active')}}</th>
                    <th>{{_lang('app.duration')}}</th>
                    <th>{{_lang('app.options')}}</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

        <!--Table Wrapper Finish-->
    </div>
</div>
<script>
var new_lang = {

};
var new_config = {
   
};
</script>
@endsection